---
  - name: Make sure the LCM refresh mode is disabled
    win_lcm5:
      refresh_mode: "Disabled"
      state: present
  - name: Install vcredist2010
    win_chocolatey:
      name: vcredist2010
  - name: Install windows features
    win_dsc5:
      resource_name="WindowsFeature"
      name={{ item }}
      ensure="Present"
    with_items:
       - web-asp-net45
       - NET-Framework-45-Features
       - Web-Server
       - Web-Performance
       - Web-static-content
       - Web-http-errors
       - Web-http-tracing
       - Web-Health
       - Web-Stat-Compression
       - Web-Windows-Auth
       - Web-Scripting-Tools
       - Web-Http-Logging
       - Web-Mgmt-Tools
